version: '3.8'
services:
  mysqldb:
    image: mysql:8.0.33
    container_name: mysqldb-container
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - main-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 10s
      timeout: 60s
  redis:
    image: redis:latest
    container_name: redis-container
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - main-network
  backend:
    image: openjdk:21-slim
    container_name: backend-container
    restart: on-failure
    depends_on:
      - mysqldb
      - redis
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prd
      - SPRING_APPLICATION_NAME=Wise's Catalog API
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - main-network

networks:
  main-network:
    name: $NETWORK_NAME
    external: true